"""baseline corpus schema

Revision ID: 0001
Revises: 
"""
import sqlalchemy as sa
from alembic import op

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('doc_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('norm_title', sa.Text(), nullable=False),
    sa.Column('authors', sa.JSON(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('xml_url', sa.Text(), nullable=True),
    sa.Column('license', sa.String(length=64), nullable=True),
    sa.Column('license_evidence', sa.Text(), nullable=True),
    sa.Column('license_flagged', sa.Boolean(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=True),
    sa.Column('topic_tags', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('split', sa.String(length=8), nullable=True),
    sa.Column('duplicate_of', sa.String(length=128), nullable=True),
    sa.Column('blacklisted', sa.Boolean(), nullable=False),
    sa.Column('blacklist_reason', sa.Text(), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('doc_id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_blacklisted'), ['blacklisted'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_doi'), ['doi'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_license'), ['license'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_norm_title'), ['norm_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_split'), ['split'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)

    op.create_table('gen_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_type', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('gen_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gen_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_gen_tasks_task_type'), ['task_type'], unique=False)

    op.create_table('releases',
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('counts', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('chunks',
    sa.Column('chunk_id', sa.String(length=200), nullable=False),
    sa.Column('doc_id', sa.String(length=128), nullable=False),
    sa.Column('section_path', sa.JSON(), nullable=False),
    sa.Column('section_type', sa.String(length=32), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('overlap_prev_tokens', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('captions', sa.JSON(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('quality', sa.JSON(), nullable=False),
    sa.Column('purpose', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.doc_id'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chunks_doc_id'), ['doc_id'], unique=False)

    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.doc_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_doc_id'), ['doc_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_doc_id'))

    op.drop_table('files')
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunks_doc_id'))

    op.drop_table('chunks')
    op.drop_table('releases')
    with op.batch_alter_table('gen_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gen_tasks_task_type'))
        batch_op.drop_index(batch_op.f('ix_gen_tasks_status'))

    op.drop_table('gen_tasks')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_split'))
        batch_op.drop_index(batch_op.f('ix_documents_source'))
        batch_op.drop_index(batch_op.f('ix_documents_norm_title'))
        batch_op.drop_index(batch_op.f('ix_documents_license'))
        batch_op.drop_index(batch_op.f('ix_documents_doi'))
        batch_op.drop_index(batch_op.f('ix_documents_blacklisted'))

    op.drop_table('documents')
    # ### end Alembic commands ###
